from __future__ import annotations

import hashlib
from xml.sax.saxutils import escape

from app.db.pronunciations import Pronunciation


def build_pls(*, language: str, items: list[Pronunciation]) -> str:
    # Deterministic ordering
    items_sorted = sorted(items, key=lambda x: (x.language, x.grapheme, x.alias))

    lexemes = []
    for it in items_sorted:
        if it.language != language:
            continue
        g = escape(it.grapheme)
        a = escape(it.alias)
        lexemes.append(
            "  <lexeme>\n"
            f"    <grapheme>{g}</grapheme>\n"
            f"    <alias>{a}</alias>\n"
            "  </lexeme>\n"
        )

    body = "".join(lexemes)
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<lexicon version="1.0"\n'
        '    xmlns="http://www.w3.org/2005/01/pronunciation-lexicon"\n'
        '    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n'
        '    xsi:schemaLocation="http://www.w3.org/2005/01/pronunciation-lexicon\n'
        '        http://www.w3.org/TR/2007/CR-pronunciation-lexicon-20071212/pls.xsd"\n'
        '    alphabet="ipa" xml:lang="' + escape(language) + '">\n\n'
        '  <!-- Generated by tts-service (consumer pronunciation overrides) -->\n'
        + body
        + "\n</lexicon>\n"
    )


def pls_hash(pls: str) -> str:
    return hashlib.sha256(pls.encode("utf-8")).hexdigest()
